# Banco de Dados Mestre de Cidades do ETS2 (Base + DLCs)
# Fonte: Koenvh1/ets2-local-radio (v1.50)

CITY_MASTER_LIST = {
    "paris": "Paris",
    "berlin": "Berlin",
    "sao_paulo": "São Paulo", # RRB Map
    "amsterdam": "Amsterdam",
    "beograd": "Belgrado",
    "roma": "Roma",
    "madrid": "Madrid",
    "lisboa": "Lisboa",
    "warszawa": "Varsóvia",
    "praha": "Praga",
    "wien": "Viena",
    "budapest": "Budapeste",
    "stockholm": "Estocolmo",
    "oslo": "Oslo",
    "helsinki": "Helsinque",
    "kobenhavn": "Copenhague",
    "istanbul": "Istambul",
    "athen": "Atenas",
    "sofia": "Sófia",
    "bucuresti": "Bucareste",
    "zagreb": "Zagreb",
    "sarajevo": "Sarajevo",
    "tirana": "Tirana",
    "skopje": "Escópia",
    "pristina": "Pristina",
    "podgorica": "Podgorica",
    "ljubljana": "Liubliana",
    "brussel": "Bruxelas",
    "luxembourg": "Luxemburgo",
    "bern": "Berna",
    "bratislava": "Bratislava",
    "tallinn": "Tallinn",
    "riga": "Riga",
    "vilnius": "Vilnius",
    "st_petersburg": "São Petersburgo",
    "moscow": "Moscou",
    "barcelona": "Barcelona",
    "milano": "Milão",
    "napoli": "Nápoles",
    "munchen": "Munique",
    "hamburg": "Hamburgo",
    "frankfurt": "Frankfurt",
    "stuttgart": "Stuttgart",
    "lyon": "Lyon",
    "marseille": "Marselha",
    "bordeaux": "Bordéus",
    "toulouse": "Toulouse",
    "nantes": "Nantes",
    "strasbourg": "Estrasburgo",
    "calais": "Calais",
    "dover": "Dover",
    "london": "Londres",
    "manchester": "Manchester",
    "birmingham": "Birmingham",
    "glasgow": "Glasgow",
    "edinburgh": "Edimburgo",
    "cardiff": "Cardiff",
    "swansea": "Swansea",
    "liverpool": "Liverpool",
    "newcastle": "Newcastle",
    "aberdeen": "Aberdeen",
    "turku": "Turku",
    "tampere": "Tampere",
    "lahti": "Lahti",
    "pori": "Pori",
    "vaasa": "Vaasa",
    "oulu": "Oulu",
    "kuopio": "Kuopio",
    "jyvaskyla": "Jyväskylä",
    "kotka": "Kotka",
    "kouvola": "Kouvola",
    "lappeenranta": "Lappeenranta",
    "savonlinna": "Savonlinna",
    "mikkeli": "Mikkeli",
    "joensuu": "Joensuu",
    "kajaani": "Kajaani",
    "kokkola": "Kokkola",
    "rovaniemi": "Rovaniemi",
    "kemi": "Kemi",
    "tornio": "Tornio",
    "hanover": "Hanôver",
    "dusseldorf": "Düsseldorf",
    "koln": "Colônia",
    "leipzig": "Leipzig",
    "dresden": "Dresden",
    "nurnberg": "Nuremberga",
    "bremen": "Bremen",
    "magdeburg": "Magdeburgo",
    "kassel": "Kassel",
    "erfurt": "Erfurt",
    "rostock": "Rostock",
    "kiel": "Kiel",
    "flensburg": "Flensburg",
    "osnabruck": "Osnabrück",
    "bielefeld": "Bielefeld",
    "munster": "Munique",
    "dortmund": "Dortmund",
    "essen": "Essen",
    "duisburg": "Duisburgo",
    "oberhausen": "Oberhausen",
    "bochum": "Bochum",
    "wuppertal": "Wuppertal",
    "bonn": "Bonn",
    "koblenz": "Coblença",
    "mainz": "Mainz",
    "mannheim": "Mannheim",
    "karlsruhe": "Karlsruhe",
    "freiburg": "Friburgo",
    "ulm": "Ulm",
    "augsburg": "Augsburgo",
    "regensburg": "Ratisbona",
    "passau": "Passau",
    "ingolstadt": "Ingolstadt",
    "furth": "Fürth",
    "erlangen": "Erlangen",
    "bayreuth": "Bayreuth",
    "bamberg": "Bamberga",
    "gera": "Gera",
    "jena": "Jena",
    "chemnitz": "Chemnitz",
    "zwickau": "Zwickau",
    "cottbus": "Cottbus",
    "potsdam": "Potsdam",
    "schwerin": "Schwerin",
}

# (O dicionário real tem centenas de entradas, adicionei as principais acima)
# Para o seu Mapa RRB, podemos adicionar as brasileiras aqui manualmente
RRB_CITIES = {
    "sao_paulo": "São Paulo",
    "rio_janeiro": "Rio de Janeiro",
    "belo_horizonte": "Belo Horizonte",
    "curitiba": "Curitiba",
    "porto_alegre": "Porto Alegre",
    "salvador": "Salvador",
    "brasilia": "Brasília",
    "fortaleza": "Fortaleza",
    "recife": "Recife",
    "manaus": "Manaus",
    "goiania": "Goiânia",
    "belem": "Belém",
    "guarulhos": "Guarulhos",
    "campinas": "Campinas",
    "sao_luis": "São Luís",
    "sao_goncalo": "São Gonçalo",
    "maceio": "Maceió",
    "duque_caxias": "Duque de Caxias",
    "natal": "Natal",
    "teresina": "Teresina",
}

CITY_MASTER_LIST.update(RRB_CITIES)
